version: '3'

services:
  koel:
    image: phanan/koel
    ports:
      - 8080:80
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=<mysql_server_ip>
      - DB_USERNAME=koel_app
      - DB_PASSWORD=koel_pass
      - DB_DATABASE=koel_db
    volumes:
      - music:/music
      - covers:/var/www/html/public/img/covers
      - search_index:/var/www/html/storage/search-indexes
    command: php artisan koel:init --no-assets -n && php artisan serve

volumes:
  music:
    driver: local
  covers:
    driver: local
  search_index:
    driver: local