version: '3'

services:
  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=koel_db
      - MYSQL_USER=koel_app
      - MYSQL_PASSWORD=koel_pass
    volumes:
      - db:/var/lib/mysql
  nginx:
    build:
      dockerfile: DockerFile.nginx
  ports:
    - 80:80
  koel:
    image: phanan/koel
    ports:
      - 8080:80
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_USERNAME=koel_app
      - DB_PASSWORD=koel_pass
      - DB_DATABASE=koel_db
    volumes:
      - music:/music
      - covers:/var/www/html/public/img/covers
      - search_index:/var/www/html/storage/search-indexes
    entrypoint: /bin/sh -c "php artisan koel:init no-assets n && apache2-foreground"
    depends_on:
      - mysql



volumes:
  db:
    driver: local
  music:
    driver: local
  covers:
    driver: local
  search_index:
    driver: local
